#!/usr/bin/env python3
"""Generate examples/README.md: a browsable index of the example library.

    uv run python scripts/examples_index.py            # (re)write examples/README.md
    uv run python scripts/examples_index.py --check    # exit 1 if it is out of date

The index is built from each example's `example.toml`, so edit the manifests, not the README.
A test keeps the committed file in sync. The docs site builds its own pattern pages from the
same manifests (docs/gen_pages.py).
"""

from __future__ import annotations

import argparse
import sys

from example_manifest import EXAMPLES_DIR, Example, discover, display_order

DOCS_URL = "https://tmtabor.io/agent-template/"
INDEX_PATH = EXAMPLES_DIR / "README.md"


def render(examples: list[Example]) -> str:
    """The markdown for examples/README.md."""
    rows = [
        f"| [`{e.name}`]({e.name}/) | {e.summary} | [recorded run]({e.name}/sample_run.md) |"
        for e in display_order(examples)
    ]
    return "\n".join(
        [
            "# Examples",
            "",
            "Working example agents for common patterns. Each folder is one pattern: run it in "
            "place, read it, or copy it into your project.",
            "",
            "```bash",
            "uv run python scripts/add_agent.py                      # pick one from a menu",
            "uv run python scripts/add_agent.py router --name support",
            "```",
            "",
            "| Example | What it shows | See it run |",
            "|---|---|---|",
            *rows,
            "",
            "Each folder contains:",
            "",
            "- `agent.py` — the agent(s) and the `run_*` helper, which returns a `RunResult`",
            "- `prompts/` — its prompt files, if it uses any",
            "- `example.toml` — its manifest: summary, smoke input, dependencies, test settings",
            "- `README.md` — when to use the pattern, and how to adapt it",
            "- `sample_run.md` — a recorded run against a real model",
            "- `test_example.py` — offline tests of its logic (where it has logic to test)",
            "- `test_live.py` — checks against a real model, run by `scripts/release_check.py`",
            "",
            f"The same pages, with the source alongside, are in the [documentation]({DOCS_URL}"
            "patterns/).",
            "",
            "<!-- Generated by scripts/examples_index.py from each example.toml. "
            "Edit the manifests, not this file. -->",
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = parser.parse_args(argv)

    text = render(discover())
    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current != text:
            print(f"{INDEX_PATH} is out of date: run scripts/examples_index.py", file=sys.stderr)
            return 1
        return 0
    INDEX_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {INDEX_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
